version: '3.7'

services:
  db-postgre:
    container_name: db-postgre-chouf
    image: postgres:12.4
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      DB_CHOUF_USER: chouf
      DB_CHOUF_PASSWORD: chouf
      DB_CHOUF_NAME: buyer
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - ./.docker/provision/postgre/init:/docker-entrypoint-initdb.d

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:6.1.0
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-broker:
    container_name: kafka-broker
    image: confluentinc/cp-kafka:6.1.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    expose:
      - 29092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS: buyer.offerPublished.event:1:1,buyer.alertSend.event:1:1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-broker:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

volumes:
  my-db:
