#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    	CREATE USER "$DB_CHOUF_USER" WITH ENCRYPTED PASSWORD 'chouf';
    	CREATE DATABASE "$DB_CHOUF_NAME";
    	GRANT ALL PRIVILEGES ON DATABASE "$DB_CHOUF_NAME" TO "$DB_CHOUF_USER";
EOSQL

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" -d "$DB_CHOUF_NAME" <<-EOSQL
  CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
EOSQL